### ISSUE TITLE
PERF: Move <script> to top of doc so it downloads sooner

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/crisper#15]
When using cripser with `--inline-script`, the standalone file ends up at the bottom of the import:

    </div><script src="elements.build.js"></script></body></html>

A vulcanized import can end up being quite large (all the css, dom-module, and svg from icons). The problem is that elements.build.js won't start loading until this entire document is parsed! On slow connections this needlessly delays the element registration :\

Current. elements.build.js doesn't start downloading until elements.html is done parsing:

<img width="824" alt="screen shot 2015-09-27 at 6 49 56 pm" src="https://cloud.githubusercontent.com/assets/238208/10126655/5dc701a6-654b-11e5-8705-260ca14f0439.png">

By moving `<script src="elements.build.js" defer></script>` to the top of the import and using `defer`, the script downloads in parallel with the html parsing and doesn't cause js errors (e.g. references to `this.$.ID` that won't exist yet).

<img width="913" alt="screen shot 2015-09-27 at 7 08 13 pm" src="https://cloud.githubusercontent.com/assets/238208/10126695/e2a4aff4-654b-11e5-8c7a-423a17e873cb.png">

@azakus wdyt?

**Comment by azakus** [comment]
SGTM, though this seems like a pretty big change. I'd like to test this with anything that tries a `document.write`, because I'm sure this will be a bugfarm for people who have those scripts.

**Comment by azakus** [comment]
I'm going to make this optional for now, default off.

**Comment by ebidel** [comment]
SGTM. LMK when you have a flag and I'd be happy to test.
