### ISSUE TITLE
Can't set `--script-in-head` to false with command line usage?

### ISSUE THREAD

**Issue by ntaoo** [PolymerLabs/crisper#27]
It looks `--script-in-head=false` doesn't work at v2.0.0.

According to the command-line-args notation rule of Boolean in `command-line-args`, the `--script-in-head` flag's value is always set to `true` regardless of the value.

> Options with a type of Boolean do not need to supply a value. Setting --flag or -f will set that option's value to true. This is the only type with special behaviour.
https://www.npmjs.com/package/command-line-args#module_command-line-args

Sorry if it's my misunderstanding.

**Comment by danbeam** [comment]
also [happening for me](https://gist.githubusercontent.com/danbeam/c8e72e61fbe5a6f49ab3/raw/56bfb118113e55c540b35e8f546aadb187152a95/gistfile1.txt)

/cc @azakus @garlicnation @tjsavage
