### ISSUE TITLE
error if last element is template

### ISSUE THREAD

**Issue by jscissr** [PolymerLabs/crisper#4]
I get these errors in the developer console after applying vulcanize and crisper:

```
[custom-style::_prepTemplate]: top-level Polymer template must not be a type-extension, found <template is=​"dom-bind">​…​</template>​ Move inside simple <template>.
[dom-template::_prepTemplate]: top-level Polymer template must not be a type-extension, found <template is=​"dom-bind">​…​</template>​ Move inside simple <template>.
[dom-repeat::_prepTemplate]: top-level Polymer template must not be a type-extension, found <template is=​"dom-bind">​…​</template>​ Move inside simple <template>.
[array-selector::_prepTemplate]: top-level Polymer template must not be a type-extension, found <template is=​"dom-bind">​…​</template>​ Move inside simple <template>.
[dom-if::_prepTemplate]: top-level Polymer template must not be a type-extension, found <template is=​"dom-bind">​…​</template>​ Move inside simple <template>.
```

I could reduce the repro to this (see also [this example](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-bind)):

index.html:
```html
<!DOCTYPE html>
<title>Demo</title>
<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
<link rel="import" href="bower_components/polymer/polymer.html">

<body>
<template is="dom-bind"></template>
```

Command line:
```sh
npm install -g vulcanize crisper
bower install Polymer/polymer
vulcanize index.html --inline-script | crisper --html build.html --js build.js
```

And then open `build.html` in Chrome.

I [found](https://github.com/Polymer/polymer/blob/master/src/mini/template.html#L32-L36) that Polymer looks for `<template>` elements just before the current `<script>`.  If it finds one it assumes that it belongs to the Polymer element being registered. However this situation happens here too (in `build.html`):

```html
<template is="dom-bind"></template>
<script src="build.js"></script>
```

And for all elements registered in `build.js` without a template, Polymer thinks this is the element's template.
An easy fix in cripser would be to simply insert any element (like a `<span>`) just before the `<script>`, if there is a `<template>` before it:

```html
<template is="dom-bind"></template>
<span></span>
<script src="build.js"></script>
```

However that is probably not the cleanest solution.

**Comment by azakus** [comment]
This undocumented feature was removed from Polymer in master: https://github.com/Polymer/polymer/issues/1827

It will be fixed in the next release of Polymer
