### ISSUE TITLE
Make sure not to break sourcemaps

### ISSUE THREAD

**Issue by azakus** [PolymerLabs/crisper#5]
Make sure not to put a semicolon on the same line as line comment

Port of https://github.com/Polymer/vulcanize/issues/64

**Comment by inureyes** [comment]
This modification makes crisper unusable with webcomponentjs+polymer. Polymer produces an error:

```
this._factory is not a function
```

**Comment by inureyes** [comment]
I guess the problem relates the javascript source map. Before this patch, source map was broken and ignored. However, now vulcanized + crisper code tries to call related external javascript files even if they are already in vulcanized source.
