### ISSUE TITLE
Crisper ignores type="text/javascript"

### ISSUE THREAD

**Issue by illiminable** [PolymerLabs/crisper#8]
This was quite confusing as to why some script was removed and some not. The logic only includes script tags that have no type or type application/javascript. There is probably still quite a bit of code that has text/javascript. 

I feel like it should extract text/javascript too. At the very least it would be useful to scan the result html and issue a warning if there are still script tags in it.

**Comment by azakus** [comment]
That seems reasonable. The best case scenario is to remove the type attribute if you can, as it is entirely unnecessary in HTML5.
