### ISSUE TITLE
Semicolon

### ISSUE THREAD

**Issue by jasonsavard** [PolymerLabs/crisper#9]
I've been successfully using this line with crisper, until I updated my crisper today.

vulcanize --inline-scripts --inline-css polymerImports.html | crisper --html vulcanized-polymer.html --js vulcanized-polymer.js

Error:
Uncaught TypeError: this._factory is not a function

It seems it's related to the "semi-colons" which I noticed there was recent update in this project.

**Comment by inureyes** [comment]
+1 . https://github.com/PolymerLabs/crisper/issues/5#issuecomment-126583585

**Comment by akashkrishnan** [comment]
:+1:

**Comment by azakus** [comment]
Can I get an example sample of code that breaks?

**Comment by azakus** [comment]
Oh, I think I see the problem. If there is *any* comment in the script, I won't include a semicolon.

**Comment by inureyes** [comment]
:+1:
